language: php

php:
  - 5.6
  - 7.0

git:
  depth: 1

cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.composer/cache

install:
  - composer install

script:
  - composer phpunit

after_success:
  - composer coveralls
